// This file is automatically generated by qtc from "largestruct.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line largestruct.qtpl:1
package templates

//line largestruct.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line largestruct.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line largestruct.qtpl:2
type LargeStruct []SmallStruct

// JSON marshaling

//line largestruct.qtpl:7
func (d LargeStruct) StreamJSON(qw422016 *qt422016.Writer) {
	//line largestruct.qtpl:7
	qw422016.N().S(`[`)
	//line largestruct.qtpl:9
	for i, r := range d {
		//line largestruct.qtpl:9
		qw422016.N().S(`{"first_name":`)
		//line largestruct.qtpl:11
		qw422016.N().Q(r.FirstName)
		//line largestruct.qtpl:11
		qw422016.N().S(`,"last_name":`)
		//line largestruct.qtpl:12
		qw422016.N().Q(r.LastName)
		//line largestruct.qtpl:12
		qw422016.N().S(`,"age":`)
		//line largestruct.qtpl:13
		qw422016.N().D(r.Age)
		//line largestruct.qtpl:13
		qw422016.N().S(`}`)
		//line largestruct.qtpl:15
		if i+1 < len(d) {
			//line largestruct.qtpl:15
			qw422016.N().S(`,`)
			//line largestruct.qtpl:15
		}
		//line largestruct.qtpl:16
	}
	//line largestruct.qtpl:16
	qw422016.N().S(`]`)
//line largestruct.qtpl:18
}

//line largestruct.qtpl:18
func (d LargeStruct) WriteJSON(qq422016 qtio422016.Writer) {
	//line largestruct.qtpl:18
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line largestruct.qtpl:18
	d.StreamJSON(qw422016)
	//line largestruct.qtpl:18
	qt422016.ReleaseWriter(qw422016)
//line largestruct.qtpl:18
}

//line largestruct.qtpl:18
func (d LargeStruct) JSON() string {
	//line largestruct.qtpl:18
	qb422016 := qt422016.AcquireByteBuffer()
	//line largestruct.qtpl:18
	d.WriteJSON(qb422016)
	//line largestruct.qtpl:18
	qs422016 := string(qb422016.B)
	//line largestruct.qtpl:18
	qt422016.ReleaseByteBuffer(qb422016)
	//line largestruct.qtpl:18
	return qs422016
//line largestruct.qtpl:18
}
