// This file is automatically generated by qtc from "smallstruct.qtpl".
// See https://github.com/valyala/quicktemplate for details.

//line smallstruct.qtpl:1
package templates

//line smallstruct.qtpl:1
import (
	qtio422016 "io"

	qt422016 "github.com/valyala/quicktemplate"
)

//line smallstruct.qtpl:1
var (
	_ = qtio422016.Copy
	_ = qt422016.AcquireByteBuffer
)

//line smallstruct.qtpl:2
type SmallStruct struct {
	FirstName string
	LastName  string
	Age       int
}

// JSON marshaling

//line smallstruct.qtpl:11
func (d *SmallStruct) StreamJSON(qw422016 *qt422016.Writer) {
	//line smallstruct.qtpl:11
	qw422016.N().S(`{"first_name":`)
	//line smallstruct.qtpl:13
	qw422016.N().Q(d.FirstName)
	//line smallstruct.qtpl:13
	qw422016.N().S(`,"last_name":`)
	//line smallstruct.qtpl:14
	qw422016.N().Q(d.LastName)
	//line smallstruct.qtpl:14
	qw422016.N().S(`,"age":`)
	//line smallstruct.qtpl:15
	qw422016.N().D(d.Age)
	//line smallstruct.qtpl:15
	qw422016.N().S(`}`)
//line smallstruct.qtpl:17
}

//line smallstruct.qtpl:17
func (d *SmallStruct) WriteJSON(qq422016 qtio422016.Writer) {
	//line smallstruct.qtpl:17
	qw422016 := qt422016.AcquireWriter(qq422016)
	//line smallstruct.qtpl:17
	d.StreamJSON(qw422016)
	//line smallstruct.qtpl:17
	qt422016.ReleaseWriter(qw422016)
//line smallstruct.qtpl:17
}

//line smallstruct.qtpl:17
func (d *SmallStruct) JSON() string {
	//line smallstruct.qtpl:17
	qb422016 := qt422016.AcquireByteBuffer()
	//line smallstruct.qtpl:17
	d.WriteJSON(qb422016)
	//line smallstruct.qtpl:17
	qs422016 := string(qb422016.B)
	//line smallstruct.qtpl:17
	qt422016.ReleaseByteBuffer(qb422016)
	//line smallstruct.qtpl:17
	return qs422016
//line smallstruct.qtpl:17
}
